export const UPDATE_LOCALES = "locales/UPDATE_LOCALES";
export const SELECT_LOCALE = "locales/SELECT_LOCALE";

export const USER_LOGIN_FETCHING = "USER_LOGIN_FETCHING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";
export const RESET_USER_LOGIN = "RESET_USER_LOGIN";

export const USER_SIGNUP_FETCHING = "USER_SIGNUP_FETCHING";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_ERROR = "USER_SIGNUP_ERROR";
export const RESET_USER_SIGNUP = "RESET_USER_SIGNUP";

export const USER_PROFILE_FETCHING = "USER_PROFILE_FETCHING";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";

export const USER_PROFILE_UPDATE_FETCHING = "USER_PROFILE_UPDATE_FETCHING";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_ERROR = "USER_PROFILE_UPDATE_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";

/* PATIENT */
export const ONLOAD_PATIENT_ASSESSMENT_PAGE = 'ONLOAD_PATIENT_ASSESSMENT_PAGE';
export const ONLOAD_PATIENT_STATUS_PAGE = 'ONLOAD_PATIENT_STATUS_PAGE';

export const PATIENT_ASSESSMENT_QUESTIONS_FETCHING =
  "PATIENT_ASSESSMENT_QUESTIONS_FETCHING";
export const PATIENT_ASSESSMENT_QUESTIONS_SUCCESS =
  "PATIENT_ASSESSMENT_QUESTIONS_SUCCESS";
export const PATIENT_ASSESSMENT_QUESTIONS_ERROR =
  "PATIENT_ASSESSMENT_QUESTIONS_ERROR";

export const PATIENT_ASSESSMENT_SUBMIT_FETCHING =
  "PATIENT_ASSESSMENT_SUBMIT_FETCHING";
export const PATIENT_ASSESSMENT_SUBMIT_SUCCESS =
  "PATIENT_ASSESSMENT_SUBMIT_SUCCESS";
export const PATIENT_ASSESSMENT_SUBMIT_ERROR =
  "PATIENT_ASSESSMENT_SUBMIT_ERROR";

export const PATIENT_RECORD_STATUS_FETCHING = "PATIENT_RECORD_STATUS_FETCHING";
export const PATIENT_RECORD_STATUS_SUCCESS = "PATIENT_RECORD_STATUS_SUCCESS";
export const PATIENT_RECORD_STATUS_ERROR = "PATIENT_RECORD_STATUS_ERROR";

/* COUNSELOR */
export const ONLOAD_COUNSELOR_PATIENT_LIST = "ONLOAD_COUNSELOR_PATIENT_LIST";
export const COUNSELOR_PATIENT_LIST_FETCHING =
  "COUNSELOR_PATIENT_LIST_FETCHING";
export const COUNSELOR_PATIENT_LIST_SUCCESS = "COUNSELOR_PATIENT_LIST_SUCCESS";
export const COUNSELOR_PATIENT_LIST_ERROR = "COUNSELOR_PATIENT_LIST_ERROR";

export const COUNSELOR_PATIENT_FETCHING = "COUNSELOR_PATIENT_FETCHING";
export const COUNSELOR_PATIENT_SUCCESS = "COUNSELOR_PATIENT_SUCCESS";
export const COUNSELOR_PATIENT_ERROR = "COUNSELOR_PATIENT_ERROR";
export const COUNSELOR_PATIENT_CLEAR = "COUNSELOR_PATIENT_CLEAR";

export const ONLOAD_COUNSELOR_APPOINTMENTS = "ONLOAD_COUNSELOR_APPOINTMENTS";
export const COUNSELOR_APPOINTMENTS_FETCHING =
  "COUNSELOR_APPOINTMENTS_FETCHING";
export const COUNSELOR_APPOINTMENTS_SUCCESS = "COUNSELOR_APPOINTMENTS_SUCCESS";
export const COUNSELOR_APPOINTMENTS_ERROR = "COUNSELOR_APPOINTMENTS_ERROR";

export const COUNSELOR_APPOINTMENTS_FOR_DATE_FETCHING =
  "COUNSELOR_APPOINTMENTS_FOR_DATE_FETCHING";
export const COUNSELOR_APPOINTMENTS_FOR_DATE_SUCCESS =
  "COUNSELOR_APPOINTMENTS_FOR_DATE_SUCCESS";
export const COUNSELOR_APPOINTMENTS_FOR_DATE_ERROR =
  "COUNSELOR_APPOINTMENTS_FOR_DATE_ERROR";

export const COUNSELOR_MAKE_APPOINTMENT_FETCHING =
  "COUNSELOR_MAKE_APPOINTMENT_FETCHING";
export const COUNSELOR_MAKE_APPOINTMENT_SUCCESS =
  "COUNSELOR_MAKE_APPOINTMENT_SUCCESS";
export const COUNSELOR_MAKE_APPOINTMENT_ERROR =
  "COUNSELOR_MAKE_APPOINTMENT_ERROR";

export const COUNSELOR_DOCTOR_LIST_FETCHING = "COUNSELOR_DOCTOR_LIST_FETCHING";
export const COUNSELOR_DOCTOR_LIST_SUCCESS = "COUNSELOR_DOCTOR_LIST_SUCCESS";
export const COUNSELOR_DOCTOR_LIST_ERROR = "COUNSELOR_DOCTOR_LIST_ERROR";

export const COUNSELOR_ASSIGN_DOCTOR_FETCHING =
  "COUNSELOR_ASSIGN_DOCTOR_FETCHING";
export const COUNSELOR_ASSIGN_DOCTOR_SUCCESS =
  "COUNSELOR_ASSIGN_DOCTOR_SUCCESS";
export const COUNSELOR_ASSIGN_DOCTOR_ERROR = "COUNSELOR_ASSIGN_DOCTOR_ERROR";

export const COUNSELOR_PATIENT_LOD_FETCHING = "COUNSELOR_PATIENT_LOD_FETCHING";
export const COUNSELOR_PATIENT_LOD_SUCCESS = "COUNSELOR_PATIENT_LOD_SUCCESS";
export const COUNSELOR_PATIENT_LOD_ERROR = "COUNSELOR_PATIENT_LOD_ERROR";

export const COUNSELOR_REJECT_PATIENT_FETCHING =
  "COUNSELOR_REJECT_PATIENT_FETCHING";
export const COUNSELOR_REJECT_PATIENT_SUCCESS =
  "COUNSELOR_REJECT_PATIENT_SUCCESS";
export const COUNSELOR_REJECT_PATIENT_ERROR = "COUNSELOR_REJECT_PATIENT_ERROR";

/* DOCTOR */
export const ONLOAD_DOCTOR_PATIENT_LIST = "ONLOAD_DOCTOR_PATIENT_LIST";
export const DOCTOR_PATIENT_LIST_FETCHING = "DOCTOR_PATIENT_LIST_FETCHING";
export const DOCTOR_PATIENT_LIST_SUCCESS = "DOCTOR_PATIENT_LIST_SUCCESS";
export const DOCTOR_PATIENT_LIST_ERROR = "DOCTOR_PATIENT_LIST_ERROR";

export const DOCTOR_PATIENT_FETCHING = "DOCTOR_PATIENT_FETCHING";
export const DOCTOR_PATIENT_SUCCESS = "DOCTOR_PATIENT_SUCCESS";
export const DOCTOR_PATIENT_ERROR = "DOCTOR_PATIENT_ERROR";
export const DOCTOR_PATIENT_CLEAR = "DOCTOR_PATIENT_CLEAR";

export const ONLOAD_DOCTOR_APPOINTMENTS = "ONLOAD_DOCTOR_APPOINTMENTS";
export const DOCTOR_APPOINTMENTS_FETCHING = "DOCTOR_APPOINTMENTS_FETCHING";
export const DOCTOR_APPOINTMENTS_SUCCESS = "DOCTOR_APPOINTMENTS_SUCCESS";
export const DOCTOR_APPOINTMENTS_ERROR = "DOCTOR_APPOINTMENTS_ERROR";

export const DOCTOR_APPOINTMENTS_FOR_DATE_FETCHING = "DOCTOR_APPOINTMENTS_FOR_DATE_FETCHING";
export const DOCTOR_APPOINTMENTS_FOR_DATE_SUCCESS = "DOCTOR_APPOINTMENTS_FOR_DATE_SUCCESS";
export const DOCTOR_APPOINTMENTS_FOR_DATE_ERROR = "DOCTOR_APPOINTMENTS_FOR_DATE_ERROR";

export const DOCTOR_MAKE_APPOINTMENT_FETCHING = "DOCTOR_MAKE_APPOINTMENT_FETCHING";
export const DOCTOR_MAKE_APPOINTMENT_SUCCESS = "DOCTOR_MAKE_APPOINTMENT_SUCCESS";
export const DOCTOR_MAKE_APPOINTMENT_ERROR = "DOCTOR_MAKE_APPOINTMENT_ERROR";

export const DOCTOR_REJECT_PATIENT_FETCHING = "DOCTOR_REJECT_PATIENT_FETCHING";
export const DOCTOR_REJECT_PATIENT_SUCCESS = "DOCTOR_REJECT_PATIENT_SUCCESS";
export const DOCTOR_REJECT_PATIENT_ERROR = "DOCTOR_REJECT_PATIENT_ERROR";

/* ADMIN */
export const ONLOAD_ADMIN_PATIENT_LIST = "ONLOAD_ADMIN_PATIENT_LIST";
export const ADMIN_GET_PATIENT_FETCHING = "ADMIN_GET_PATIENT_FETCHING";
export const ADMIN_GET_PATIENT_SUCCESS = "ADMIN_GET_PATIENT_SUCCESS";
export const ADMIN_GET_PATIENT_ERROR = "ADMIN_GET_PATIENT_ERROR";

export const ADMIN_REMOVE_PATIENT_FETCHING = "ADMIN_REMOVE_PATIENT_FETCHING";
export const ADMIN_REMOVE_PATIENT_SUCCESS = "ADMIN_REMOVE_PATIENT_SUCCESS";
export const ADMIN_REMOVE_PATIENT_ERROR = "ADMIN_REMOVE_PATIENT_ERROR";

export const ADMIN_GET_COUNSELOR_FETCHING = "ADMIN_GET_COUNSELOR_FETCHING";
export const ADMIN_GET_COUNSELOR_SUCCESS = "ADMIN_GET_COUNSELOR_SUCCESS";
export const ADMIN_GET_COUNSELOR_ERROR = "ADMIN_GET_COUNSELOR_ERROR";

export const ADMIN_REMOVE_COUNSELOR_FETCHING = "ADMIN_REMOVE_COUNSELOR_FETCHING";
export const ADMIN_REMOVE_COUNSELOR_SUCCESS = "ADMIN_REMOVE_COUNSELOR_SUCCESS";
export const ADMIN_REMOVE_COUNSELOR_ERROR = "ADMIN_REMOVE_COUNSELOR_ERROR";

export const ADMIN_GET_DOCTOR_FETCHING = "ADMIN_GET_DOCTOR_FETCHING";
export const ADMIN_GET_DOCTOR_SUCCESS = "ADMIN_GET_DOCTOR_SUCCESS";
export const ADMIN_GET_DOCTOR_ERROR = "ADMIN_GET_DOCTOR_ERROR";

export const ADMIN_REMOVE_DOCTOR_FETCHING = "ADMIN_REMOVE_DOCTOR_FETCHING";
export const ADMIN_REMOVE_DOCTOR_SUCCESS = "ADMIN_REMOVE_DOCTOR_SUCCESS";
export const ADMIN_REMOVE_DOCTOR_ERROR = "ADMIN_REMOVE_DOCTOR_ERROR";

export const ADMIN_CREATE_USER_FETCHING = "ADMIN_CREATE_USER_FETCHING";
export const ADMIN_CREATE_USER_SUCCESS = "ADMIN_CREATE_USER_SUCCESS";
export const ADMIN_CREATE_USER_ERROR = "ADMIN_CREATE_USER_ERROR";

export const ADMIN_REPORT_PARAMETERS_FETCHING = "ADMIN_REPORT_PARAMETERS_FETCHING";
export const ADMIN_REPORT_PARAMETERS_SUCCESS = "ADMIN_REPORT_PARAMETERS_SUCCESS";
export const ADMIN_REPORT_PARAMETERS_ERROR = "ADMIN_REPORT_PARAMETERS_ERROR";

export const ADMIN_REPORT_FETCHING = "ADMIN_REPORT_FETCHING";
export const ADMIN_REPORT_SUCCESS = "ADMIN_REPORT_SUCCESS";
export const ADMIN_REPORT_ERROR = "ADMIN_REPORT_ERROR";


/* Gui */
export const OPEN_MESSAGE_MODAL = "OPEN_MESSAGE_MODAL";
export const CLOSE_MESSAGE_MODAL = "CLOSE_MESSAGE_MODAL";