package com.medicalassistance.core.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.medicalassistance.core.common.AuthorityName;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.ZonedDateTime;
import java.util.Date;
import java.util.Set;

@Document("users")
public class User extends DateDomainObject {
    @Id
    private String userId;

    private String fullName;

    private String addressLine;

    private String city;

    private String province;

    private String country;

    private ZonedDateTime dateOfBirth;

    private String phoneNumber;

    @Indexed(unique = true)
    private String emailAddress;

    @JsonIgnore
    private String password;

    private String registrationNumber;

    @JsonIgnore
    private Date lastPasswordResetDate;

    private boolean passwordAutoGenerated;

    private Set<AuthorityName> authorities;

    private boolean deleted;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getAddressLine() {
        return addressLine;
    }

    public void setAddressLine(String addressLine) {
        this.addressLine = addressLine;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public ZonedDateTime getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(ZonedDateTime dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmailAddress() {
        return emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRegistrationNumber() {
        return registrationNumber;
    }

    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    public Date getLastPasswordResetDate() {
        return lastPasswordResetDate;
    }

    public void setLastPasswordResetDate(Date lastPasswordResetDate) {
        this.lastPasswordResetDate = lastPasswordResetDate;
    }

    public boolean isPasswordAutoGenerated() {
        return passwordAutoGenerated;
    }

    public void setPasswordAutoGenerated(boolean passwordAutoGenerated) {
        this.passwordAutoGenerated = passwordAutoGenerated;
    }

    public Set<AuthorityName> getAuthorities() {
        return authorities;
    }

    public void setAuthorities(Set<AuthorityName> authorities) {
        this.authorities = authorities;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
}